name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build Dockerfile, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpk9ff62ac0jbv65lep
          CR_REPOSITORY: testnew
          IMAGE_TAG: latest
        run: |
          echo "${{ vars.ENV_PROD }}" >> .env
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        env:
          CR_REGISTRY: crpk9ff62ac0jbv65lep
          CR_REPOSITORY: testnew
          IMAGE_TAG: latest
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: testnew
          folder-id: b1gar10pd0fbvh7rvcap
          revision-service-account-id: ajekqaon1n6suboa0uav
          revision-cores: 1
          revision-memory: 384Mb
          revision-core-fraction: 50
          revision-concurrency: 1
          revision-image-url: cr.yandex/crpk9ff62ac0jbv65lep/testnew:latest
          revision-execution-timeout: 10
